import scripts.qcommands.new
import scripts.qcommands.join
import scripts.qcommands.state
import scripts.qcommands.circuit
import scripts.qcommands.probs
import scripts.qcommands.apply
import scripts.qcommands.measure
import scripts.qcommands.rename
import scripts.qcommands.timer
import scripts.qcommands.if_then
import scripts.qcommands.if_then_else
import scripts.qcommands.for_each
import scripts.qcommands.execute
import scripts.qcommands.delete
import scripts.qcommands.keep
import scripts.qcommands.list
import scripts.qcommands.quit
import scripts.qcommands.help
import scripts.qcommands.verifiers